try:
    raise ValueError("foo")
except:
    print(1)
    raise